name: music_app Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/music_app:latest

jobs:
  build-jar:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: music-app-jar
          path: target/*.jar

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download JAR 
        uses: actions/download-artifact@v4
        with:
          name: music-app-jar
          path: target/

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.AWS_KNOWN_HOSTS }}

      - name: Deploy Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} <<EOF
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo yum update -y || sudo apt-get update -y
              sudo yum install -y docker || sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker \$USER
            fi

            # Pull latest image
            docker pull $DOCKER_IMAGE

            # Stop and remove old container if exists
            docker stop music_app || true
            docker rm music_app || true

            # Run new container
            docker run -d --name music_app -p 80:8080 $DOCKER_IMAGE
          EOF
